#lang racket
(require (planet dyoo/while-loop:1:=1))
(require "etc.rkt")
(provide comment-symbol)
(provide read-code)
(define (identifier)
 (list->string (collect
                (if (subsequent? (peek-char))
                 (list (read-char))
                 #f))))

(define (initial? c)
 (or (char-alphabetic? c)
     (special-initial? c)))

(define (peek? s (skip 0))
 (define c (peek-char (current-input-port) skip))
 (and (not (eof-object? c))
      (char=? c (string-ref s 0))))

(define(lang)
 (whitespace)
	(if(equal?(peek-string 5 0)"#lang")
(string-append	(read-line)"\n")
	""))

(define (read-code)
(cons(lang)
 (collect
  (define x (read1))
  (if (eof-object? x)
   #f
   (list x)))))

(define (read1)
 (whitespace)
 (cond
  ((eof-object? (peek-char))
   (peek-char))
  ((peek? "#")
   (cond
    ((peek? "'" 1)
     (read-char)
     (read-char)
     (list 'syntax (read1)))
    ((peek? "`" 1)
     (read-char)
     (read-char)
     (list 'quasisyntax (read1)))
    ((peek? "," 1)
     (read-char)
     (read-char)
     (if (peek? "@")
      (begin
       (read-char)
       (list 'unsyntax-splicing (read1)))
      (list 'unsyntax (read1))))
    ((peek? ":" 1)
     (read))
    ((peek? "\\" 1)
     (read))
    (else
     (let ((s (identifier)))
      (case s
       (("#")
        (list->vector (read)))
       (("#f" "#F")
        #f)
       (("#t" "#T")
        #t)
       (else
        (string->symbol s)))))))
  ((peek? "'")
   (read-char)
   (list 'quote (read1)))
  ((peek? "(")
   (read-char)
   (let loop ()
    (whitespace)
    (cond
     ((eof-object? (peek-char))
      (error "unterminated list"))
     ((peek? ")")
      (read-char)
      '())
     ((peek? ".")
      (let ((s (identifier)))
       (if (string=? s ".")
        (let ((x (read)))
         (while (not (peek? ")"))
          (whitespace)
          (cond
           ((eof-object? (peek-char))
            (error "expected ')'"))
           ((peek? ";")
            (read-line))))
         (read-char)
         x)
        (cons (string->symbol s) (loop)))))
     (else
      (cons (read1) (loop))))))
  ((peek? ",")
   (read-char)
   (if (peek? "@")
    (begin
     (read-char)
     (list 'unquote-splicing (read1)))
    (list 'unquote (read1))))
  ((peek? ";")
   (list comment-symbol (read-line)))
  ((peek? "`")
   (read-char)
   (list 'quasiquote (read1)))
  (else
   (read))))

(define (special-initial? c)
 (string-contains? "!#$%&*/:<=>?^_~" (make-string 1 c)))

(define (special-subsequent? c)
 (string-contains? "+-.@" (make-string 1 c)))

(define (subsequent? c)
 (or (initial? c)
     (char-numeric? c)
     (special-subsequent? c)))

(define (whitespace)
 (when (and (not (eof-object? (peek-char)))
            (char-whitespace? (peek-char)))
  (read-char)
  (whitespace)))

(define comment-symbol (gensym))
